
CREATE TABLE Plano(
    Id NUMBER NOT NULL,
    Nome VARCHAR2(25) NOT NULL,
    Valor FLOAT NOT NULL,
    QualidadeMax NUMBER(5) NOT NULL,
    QtdTelas NUMBER(1) NOT NULL,
    NumMaxPerfis NUMBER(1) NOT NULL,
    CONSTRAINT PK_PLANO PRIMARY KEY(Id),
    CONSTRAINT UN_PLANO_NOME UNIQUE(Nome),
    CONSTRAINT CK_PLANO_QLDSTREAM CHECK(QualidadeMax in (360,480,720,1080,2160))
);

CREATE TABLE Usuario(
    CPF NUMBER(11) NOT NULL,
    Nome VARCHAR2(60) NOT NULL,
    Email VARCHAR2(255) NOT NULL,
    DataNasc DATE NOT NULL,
    Plano NUMBER NOT NULL,
    CONSTRAINT PK_USUARIO PRIMARY KEY(CPF),
    CONSTRAINT FK_USUARIO_PLANO FOREIGN KEY(Plano)
        REFERENCES Plano(Id) ON DELETE SET NULL,
    CONSTRAINT UN_USUARIO_EMAIL UNIQUE(Email)
);

CREATE TABLE Dispositivo(
    Usuario NUMBER(11) NOT NULL,
    Nome VARCHAR2(20) NOT NULL,
    SistOperacional VARCHAR2(20) NOT NULL,
    CONSTRAINT PK_DISPOSITIVO PRIMARY KEY(Usuario, Nome),
    CONSTRAINT FK_DISPOSITIVO_USUARIO FOREIGN KEY(Usuario)
            REFERENCES Usuario(CPF) ON DELETE CASCADE
);

CREATE TABLE Acesso(
    Usuario NUMBER(11) NOT NULL,
    NomeDisp VARCHAR2(20) NOT NULL,
    IPv4 VARCHAR2(15) NOT NULL,
    HoraAcesso TIMESTAMP NOT NULL,
    CONSTRAINT PK_ACESSO PRIMARY KEY(Usuario, NomeDisp, HoraAcesso),
    CONSTRAINT FK_ACESSO_USUARIO FOREIGN KEY(Usuario)
            REFERENCES Usuario(CPF) ON DELETE CASCADE,
    CONSTRAINT FK_ACESSO_DISPOSITIVO FOREIGN KEY(Usuario, NomeDisp)
            REFERENCES Dispositivo(Usuario, Nome) ON DELETE CASCADE
);

CREATE TABLE FormaDePagamento(
    Usuario NUMBER(11) NOT NULL,
    Tipo VARCHAR2(20) NOT NULL,
    CONSTRAINT PK_FORMADEPAGAMENTO PRIMARY KEY(Usuario),
    CONSTRAINT FK_FORMADEPAGAMENTO_USUARIO FOREIGN KEY(Usuario)
        REFERENCES Usuario(CPF) ON DELETE CASCADE,
    CONSTRAINT TIPOPAGAMENTO CHECK (Tipo IN ('Cartão De Crédito', 'Débito Automático', 'PayPal'))
);

CREATE TABLE NumCartao(
    NumCartao NUMBER(18) NOT NULL,
    Bandeira VARCHAR2(25) NOT NULL,
    DataVenc DATE NOT NULL,
    CodSeg NUMBER(3) NOT NULL,
    NomeTitular VARCHAR2(60) NOT NULL,
    CONSTRAINT PK_NUMCARTAO PRIMARY KEY(NumCartao),
    CONSTRAINT BANDEIRACARTAO CHECK (Bandeira IN ('Visa', 'Mastercard', 'American Express', 'Elo'))
);

CREATE TABLE CartaoCredito(
    Usuario NUMBER(11) NOT NULL,
    NumCartao NUMBER(18) NOT NULL,
    CONSTRAINT PK_CARTAOCREDITO PRIMARY KEY(Usuario),
    CONSTRAINT FK_CARTAOCREDITO_FPAGAMENTO FOREIGN KEY(Usuario)
        REFERENCES FormaDePagamento(Usuario) ON DELETE CASCADE,
    CONSTRAINT FK_CARTAOCREDITO_NUMCARTAO FOREIGN KEY(NumCartao)
        REFERENCES NumCartao(NumCartao) ON DELETE CASCADE
);

CREATE TABLE DebitoAutomatico(
    Usuario NUMBER(11) NOT NULL,
    CPF NUMBER(11) NOT NULL,
    Nome VARCHAR2(60) NOT NULL,
    Sobrenome VARCHAR2(60) NOT NULL,
    Banco VARCHAR2(30) NOT NULL,
    Agencia NUMBER(5) NOT NULL,
    Conta NUMBER(20) NOT NULL,
    CONSTRAINT PK_DEBITOAUT PRIMARY KEY(Usuario),
    CONSTRAINT FK_DEBITOAUT_FPAGAMENTO FOREIGN KEY(Usuario)
        REFERENCES FormaDePagamento(Usuario) ON DELETE CASCADE,
    CONSTRAINT BANCODEBITO CHECK (Banco in ('Banco do Brasil', 'Bradesco', 'Itaú', 'Santander'))
);

CREATE TABLE PayPal(
    Usuario NUMBER(11) NOT NULL,
    Email VARCHAR2(255) NOT NULL,
    Senha VARCHAR2(30) NOT NULL,
    CONSTRAINT PK_PAYPAL PRIMARY KEY(Usuario),
    CONSTRAINT FK_PAYPAL_FPAGAMENTO FOREIGN KEY(Usuario)
        REFERENCES FormaDePagamento(Usuario) ON DELETE CASCADE
);

CREATE TABLE Faturas(
    CodFatura NUMBER NOT NULL,
    Periodo DATE NOT NULL,
    Usuario NUMBER(11) NOT NULL,
    Plano NUMBER NOT NULL,
    CONSTRAINT PK_FATURAS PRIMARY KEY(CodFatura),
    CONSTRAINT FK_FATURAS_FPAGAMENTO FOREIGN KEY(Usuario)
        REFERENCES FormaDePagamento(Usuario) ON DELETE CASCADE,
    CONSTRAINT FK_FATURAS_PLANO FOREIGN KEY(Plano)
        REFERENCES Plano(Id) ON DELETE CASCADE,
    CONSTRAINT UN_FATURAS UNIQUE(Periodo, Usuario, Plano)
);

CREATE TABLE Idioma(
    Id NUMBER NOT NULL,
    Nome VARCHAR2(40) NOT NULL,
    CONSTRAINT PK_IDIOMA PRIMARY KEY(Id)
);

CREATE TABLE Perfil(
    Alias VARCHAR2(25) NOT NULL,
    Usuario NUMBER(11) NOT NULL,
    Tipo VARCHAR2(8) NOT NULL,
    CONSTRAINT PK_PERFIL PRIMARY KEY(Alias, Usuario),
    CONSTRAINT FK_PERFIL_USUARIO FOREIGN KEY(Usuario)
        REFERENCES Usuario(CPF) ON DELETE CASCADE,
    CONSTRAINT CK_PERFIL_TIPO CHECK(Tipo in ('Adulto', 'Infantil'))
);

CREATE TABLE Adulto(
    Alias VARCHAR2(25) NOT NULL,
    Usuario NUMBER(11) NOT NULL,
    QualidStreaming NUMBER(5) NOT NULL,
    Legenda NUMBER NOT NULL,
    Idioma NUMBER NOT NULL,
    CONSTRAINT PK_ADULTO PRIMARY KEY(Alias, Usuario),
    CONSTRAINT FK_ADULTO_PERFIL FOREIGN KEY(Alias, Usuario)
        REFERENCES Perfil(Alias, Usuario) ON DELETE CASCADE,
    CONSTRAINT CK_ADULTO_QLDSTREAM CHECK(QualidStreaming in (360,480,720,1080,2160))
);

CREATE TABLE Infantil(
    Alias VARCHAR2(25) NOT NULL,
    Usuario NUMBER(11) NOT NULL,
    FaixaEtaria NUMBER(2) NOT NULL,
    Adulto VARCHAR2(25) NOT NULL,
    CONSTRAINT PK_INFANTIL PRIMARY KEY(Alias, Usuario),
    CONSTRAINT FK_INFANTIL_PERFIL FOREIGN KEY(Alias, Usuario)
        REFERENCES Perfil(Alias, Usuario) ON DELETE CASCADE,
    CONSTRAINT FK_INFANTIL_ADULTO FOREIGN KEY(Adulto, Usuario)
        REFERENCES Adulto(Alias, Usuario) ON DELETE CASCADE
);

CREATE TABLE Amizade(
    Perfil1 VARCHAR2(25) NOT NULL,
    Usuario1 NUMBER(11) NOT NULL,
    Perfil2 VARCHAR2(25) NOT NULL,
    Usuario2 NUMBER(11) NOT NULL,
    DataAceitacao DATE,
    DataSolicitacao DATE NOT NULL,
    CONSTRAINT PK_AMIZADE PRIMARY KEY(Perfil1, Usuario1, Perfil2, Usuario2),
    CONSTRAINT FK_AMIZADE_PERFIL1 FOREIGN KEY(Perfil1, Usuario1)
        REFERENCES Perfil(Alias, Usuario) ON DELETE CASCADE,
    CONSTRAINT FK_AMIZADE_PERFIL2 FOREIGN KEY(Perfil2, Usuario2)
        REFERENCES Perfil(Alias, Usuario) ON DELETE CASCADE
);

CREATE TABLE Serie(
    Id NUMBER NOT NULL,
    Titulo VARCHAR2(60) NOT NULL,
    AnoLancamento NUMBER(4) NOT NULL,
    QtdTemporadas NUMBER NOT NULL,
    CONSTRAINT PK_SERIE PRIMARY KEY(Id),
    CONSTRAINT UN_SERIE UNIQUE(Titulo, AnoLancamento)
);

CREATE TABLE Temporada(
    Serie NUMBER NOT NULL,
    Numero NUMBER NOT NULL,
    Titulo VARCHAR2(60),
    QtdEpisodios NUMBER,
    CONSTRAINT PK_TEMPORADA PRIMARY KEY(Serie, Numero),
    CONSTRAINT FK_TEMPORADA_SERIE FOREIGN KEY(Serie)
        REFERENCES Serie(Id) ON DELETE CASCADE
);

CREATE TABLE Media(
    Id NUMBER NOT NULL,
    Titulo VARCHAR2(60) NOT NULL,
    AnoLancamento NUMBER NOT NULL,
    Thumb VARCHAR2(255) NOT NULL,
    Duracao NUMBER(3) NOT NULL,
    Sinopse VARCHAR2(300) NOT NULL,
    ClassificacaoEtaria NUMBER(2),
    Avaliacao NUMBER(3),
    NumeroDoEp NUMBER,
    Serie NUMBER,
    Temporada NUMBER,
    CONSTRAINT PK_MEDIA PRIMARY KEY(Id),
    CONSTRAINT UN_MEDIA UNIQUE(Titulo, AnoLancamento),
    CONSTRAINT FK_MEDIA_TEMPORADA FOREIGN KEY(Serie, Temporada)
        REFERENCES Temporada(Serie, Numero) ON DELETE CASCADE,
    CONSTRAINT CK_MEDIA CHECK(Avaliacao <= 100 AND Avaliacao >= 0)
);

CREATE TABLE Recomendacoes(
    Alias VARCHAR2(25) NOT NULL,
    Usuario NUMBER(11) NOT NULL,
    PerfilAmigo VARCHAR2(25) NOT NULL,
    UsuarioAmigo NUMBER(11) NOT NULL,
    Media NUMBER NOT NULL,
    Data DATE NOT NULL,
    Comentario VARCHAR2(300),
    CONSTRAINT PK_RECOMENDACOES PRIMARY KEY(Alias, Usuario, PerfilAmigo, UsuarioAmigo, Media, Data),
    CONSTRAINT FK_RECOMENDACOES_PERFIL FOREIGN KEY(Alias, Usuario)
        REFERENCES Perfil(Alias, Usuario) ON DELETE CASCADE,
    CONSTRAINT FK_RECOMENDACOES_AMIZADE FOREIGN KEY(Alias, Usuario, PerfilAmigo, UsuarioAmigo)
        REFERENCES Amizade(Perfil1, Usuario1, Perfil2, Usuario2) ON DELETE CASCADE,
    CONSTRAINT FK_RECOMENDACOES_MEDIA FOREIGN KEY(Media)
        REFERENCES Media(Id) ON DELETE CASCADE
);

CREATE TABLE LegendaMedia(
    Media NUMBER NOT NULL,
    Idioma NUMBER NOT NULL,
    CONSTRAINT PK_LEGENDAMEDIA PRIMARY KEY(Media, Idioma),
    CONSTRAINT FK_LEGENDAMEDIA_MEDIA FOREIGN KEY(Media)
        REFERENCES Media(Id) ON DELETE CASCADE,
    CONSTRAINT FK_LEGENDAMEDIA_IDIOMA FOREIGN KEY(Idioma)
        REFERENCES Idioma(Id) ON DELETE CASCADE
);

CREATE TABLE AudioMedia(
    Media NUMBER NOT NULL,
    Idioma NUMBER NOT NULL,
    Original NUMBER(1) NOT NULL,
    CONSTRAINT PK_AUDIOMEDIA PRIMARY KEY(Media, Idioma),
    CONSTRAINT FK_AUDIOMEDIA_MEDIA FOREIGN KEY(Media)
        REFERENCES Media(Id) ON DELETE CASCADE,
    CONSTRAINT FK_AUDIOMEDIA_IDIOMA FOREIGN KEY(Idioma)
        REFERENCES Idioma(Id) ON DELETE CASCADE
);

CREATE TABLE Ator(
    CPF NUMBER(11) NOT NULL,
    Nome VARCHAR2(60) NOT NULL,
    CONSTRAINT PK_ATOR PRIMARY KEY(CPF)
);

CREATE TABLE Diretor(
    CPF NUMBER(11) NOT NULL,
    Nome VARCHAR2(60) NOT NULL,
    CONSTRAINT PK_DIRETOR PRIMARY KEY(CPF)
);

CREATE TABLE Atuacoes(
    CPF NUMBER(11) NOT NULL,
    Media NUMBER NOT NULL,
    CONSTRAINT PK_ATUACOES PRIMARY KEY(CPF, Media),
    CONSTRAINT FK_ATUACOES_ATOR FOREIGN KEY(CPF)
        REFERENCES Ator(CPF) ON DELETE CASCADE,
    CONSTRAINT FK_ATUACOES_MEDIA FOREIGN KEY(Media)
        REFERENCES Media(Id) ON DELETE CASCADE
);

CREATE TABLE Direcoes(
    CPF NUMBER(11) NOT NULL,
    Media NUMBER NOT NULL,
    Cargo VARCHAR2(35) NOT NULL,
    CONSTRAINT PK_DIRECOES PRIMARY KEY(CPF, Media),
    CONSTRAINT FK_DIRECOES_ATOR FOREIGN KEY(CPF)
        REFERENCES Diretor(CPF) ON DELETE CASCADE,
    CONSTRAINT FK_DIRECOES_MEDIA FOREIGN KEY(Media)
        REFERENCES Media(Id) ON DELETE CASCADE
);

CREATE TABLE Generos(
    Nome VARCHAR2(15) NOT NULL,
    Descricao VARCHAR2(60) NOT NULL,
    CONSTRAINT PK_GENEROS PRIMARY KEY(Nome)
);

CREATE TABLE GenerosMedia(
    Genero VARCHAR2(15) NOT NULL,
    Media NUMBER NOT NULL,
    CONSTRAINT PK_GENEROSMEDIA PRIMARY KEY(Genero, Media),
    CONSTRAINT FK_GENEROSMEDIA_GENERO FOREIGN KEY(Genero)
        REFERENCES Generos(Nome) ON DELETE CASCADE,
    CONSTRAINT FK_GENEROSMEDIA_MEDIA FOREIGN KEY(Media)
        REFERENCES Media(Id) ON DELETE CASCADE
);

CREATE TABLE PreferenciaGenero(
    Alias VARCHAR2(25) NOT NULL,
    Usuario NUMBER NOT NULL,
    Genero VARCHAR2(15) NOT NULL,
    Nota FLOAT NOT NULL,
    CONSTRAINT PK_PREFERENCIAGENERO PRIMARY KEY(Alias, Usuario, Genero),
    CONSTRAINT FK_PREFERENCIAGENERO_PERFIL FOREIGN KEY(Alias, Usuario)
        REFERENCES Perfil(Alias, Usuario) ON DELETE CASCADE,
    CONSTRAINT FK_PREFERENCIAGENERO_GENERO FOREIGN KEY(Genero)
        REFERENCES Generos(Nome) ON DELETE CASCADE
);

CREATE TABLE Exibicao(
	Alias VARCHAR2(25) NOT NULL,
	Usuario NUMBER(11) NOT NULL,
	Media NUMBER NOT NULL,
	Data DATE NOT NULL,
	TempoAssistido NUMBER(3) NOT NULL,
	CONSTRAINT PK_EXIBICAO PRIMARY KEY(Alias, Usuario, Media, Data),
	CONSTRAINT FK_EXIBICAO_PERFIL FOREIGN KEY(Alias, Usuario)
        REFERENCES Perfil(Alias, Usuario),
    CONSTRAINT FK_EXIBICAO_MEDIA FOREIGN KEY(Media)
        REFERENCES Media(Id)
);

CREATE TABLE Avaliacao(
    Alias VARCHAR2(25) NOT NULL,
	Usuario NUMBER(11) NOT NULL,
	Media NUMBER NOT NULL,
	Data DATE NOT NULL,
    Nota NUMBER(3) NOT NULL,
    CONSTRAINT PK_AVALIACAO PRIMARY KEY(Alias, Usuario, Media, Data),
    CONSTRAINT FK_AVALIACAO_PERFIL FOREIGN KEY(Alias, Usuario)
        REFERENCES Perfil(Alias, Usuario),
    CONSTRAINT FK_AVALIACAO_MEDIA FOREIGN KEY(Media)
        REFERENCES Media(Id),
    CONSTRAINT CK_AVALIACAO CHECK(Nota <= 100 AND Nota >= 0)
);

CREATE TABLE Opiniao(
    Alias VARCHAR2(25) NOT NULL,
	Usuario NUMBER(11) NOT NULL,
	Media NUMBER NOT NULL,
	Data DATE NOT NULL,
    Texto VARCHAR2(500) NOT NULL,
    CONSTRAINT PK_OPINIAO PRIMARY KEY(Alias, Usuario, Media),
    CONSTRAINT FK_OPINIAO_PERFIL FOREIGN KEY(Alias, Usuario)
        REFERENCES Adulto(Alias, Usuario),
    CONSTRAINT FK_OPINIAO_MEDIA FOREIGN KEY(Media)
        REFERENCES Media(Id)
);